### ISSUE TITLE
RPIP-4 voting weight formula

### ISSUE THREAD

**Issue by harpocryptes** [rocket-pool/RPIPs#6]
The formula is stated as:

 ```weight = min( (registrationDate - currentDate) / 100, 1)```

First, `currentDate` is greater than `registrationDate`, so `registrationDate - currentDate` is negative. Shouldn't it be `currentDate - registrationDate`?

I also don't see the unit specified, is it in days, i.e. maximum weight reached 100 days after registration?

**Comment by VVander** [comment]
Thanks for your review! You are correct that that the weight calculation is reversed. I've submitted a PR to fix this and add clarification for the date variables. Based on this edit, these variables will be integer level precision, which I think is sufficient for this purpose.

**Comment by htimsk** [comment]
Corrected documentation via [PR#7](https://github.com/rocket-pool/RPIPs/pull/7)
